// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCudgY7SOQjP3BX2M33OvInKhm4hbrulgA',
    appId: '1:767720007523:web:d32dfad6ca944b67399556',
    messagingSenderId: '767720007523',
    projectId: 'contact-app-dcf6b',
    authDomain: 'contact-app-dcf6b.firebaseapp.com',
    storageBucket: 'contact-app-dcf6b.firebasestorage.app',
    measurementId: 'G-303LRX86EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsd-yaknarlaoVkVeYXTZlTFI7RlPGUj8',
    appId: '1:767720007523:android:8249ebab58fd4fd0399556',
    messagingSenderId: '767720007523',
    projectId: 'contact-app-dcf6b',
    storageBucket: 'contact-app-dcf6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbqDWG06Qmyzw8SbZd5EPgRb90UY8xxPo',
    appId: '1:767720007523:ios:9f3862af830d12a0399556',
    messagingSenderId: '767720007523',
    projectId: 'contact-app-dcf6b',
    storageBucket: 'contact-app-dcf6b.firebasestorage.app',
    iosBundleId: 'com.example.contactApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbqDWG06Qmyzw8SbZd5EPgRb90UY8xxPo',
    appId: '1:767720007523:ios:9f3862af830d12a0399556',
    messagingSenderId: '767720007523',
    projectId: 'contact-app-dcf6b',
    storageBucket: 'contact-app-dcf6b.firebasestorage.app',
    iosBundleId: 'com.example.contactApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCudgY7SOQjP3BX2M33OvInKhm4hbrulgA',
    appId: '1:767720007523:web:0e7f6652c8e24c1e399556',
    messagingSenderId: '767720007523',
    projectId: 'contact-app-dcf6b',
    authDomain: 'contact-app-dcf6b.firebaseapp.com',
    storageBucket: 'contact-app-dcf6b.firebasestorage.app',
    measurementId: 'G-N6Q77JDF7W',
  );
}
